### ISSUE TITLE
Manifest

### ISSUE THREAD

**Issue by jpcaparas** [pixelfusion/front-end-scripts#22]
When running `front-end-scripts build` a manifest **does not get emitted** with the chunk hash, something to do the effect of:

```
{
  "client/css/index.css": "public/index.c26f4bbc2e0a934326af.css",
  "client/js/index.js": "public/index.c26f4bbc2e0a934326af.js"
}
```

Can we use [this](https://github.com/danethurber/webpack-manifest-plugin)?

**Comment by hally9k** [comment]
@jpcaparas Yeah I'd be keen to see a PR of this added.

**Comment by jpcaparas** [comment]
Great, I'll work on it then.

**Comment by jpcaparas** [comment]
Hi @hally9k,

Just realised that the `extract-text-webpack-plugin` already does this after running `yarn run build`:

<img width="322" alt="screen shot 2017-05-25 at 10 31 58 am" src="https://cloud.githubusercontent.com/assets/2406808/26428409/9a5cc502-4135-11e7-8eec-a855fbdd0ce1.png">

Closing it now.
